name: Pull Request CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
        - os: windows-latest
          vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          openssl_home: C:\Program Files\OpenSSL-Win64
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Version Info
        run: mvn -version
      - if: matrix.os != 'windows-latest'
        name: OpenSSL Library Version Info
        run: openssl version -v
      - if: matrix.os == 'windows-latest'
        name: Install full OpenSSL library
        run: |
          choco install --no-progress openssl
      - if: matrix.os != 'windows-latest'
        name: Build with Maven
        run: mvn -B package --file pom.xml
      - if: matrix.os == 'windows-latest'
        name: Build with Microsoft Visual Studio native tools command prompt and Maven
        env:
          VCVARS: ${{ matrix.vcvars }}
          OPENSSL_HOME: ${{ matrix.openssl_home }}
        shell: cmd
        run: |
          call "%VCVARS%"
          mvn -B package --file pom.xml -Dorg.wildfly.openssl.path="%OPENSSL_HOME%"\bin
